In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X-X.mean()

layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y=net(torch.rand(4,8))
Y.mean()

tensor(-1.6298e-09, grad_fn=<MeanBackward0>)

In [12]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):  # in_units:输入数,units:输出数
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)

linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.0374, -2.5660,  0.0167],
        [-0.6826,  1.0408,  1.8307],
        [ 1.3260,  0.2507,  0.0273],
        [ 0.7953,  0.3506, -0.2179],
        [ 1.5023, -0.4498, -0.6834]], requires_grad=True)

In [22]:
linear(torch.rand(2,5))

tensor([[1.3178, 0.0000, 1.0640],
        [1.8936, 0.0000, 0.0000]])

In [26]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
print(net(torch.rand(2,64)))
net

tensor([[10.6795],
        [ 4.6666]])


Sequential(
  (0): MyLinear()
  (1): MyLinear()
)

Exercises

In [71]:
from torch import fft

class FourierLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,x):
        x=fft.fftn(x)           # 对输入的张量x进行快速傅里叶变换
        x=x[:,:,:x.shape[2]//2] # 取出第三个维度的前半部分,即去掉直流分量和镜像分量
        return x

X=torch.rand(1,2,5)
net=FourierLayer()
net(X)

tensor([[[ 6.8317+0.0000j, -1.0313+0.0917j],
         [-0.0278+0.0000j,  0.5520+0.7611j]]])