In [6]:
import torch
from torch import nn
from torch.nn import functional as F

x=torch.arange(4)
torch.save(x,'../data/x-file')
x2=torch.load('../data/x-file')
x2

tensor([0, 1, 2, 3])

In [7]:
y=torch.zeros(4)
torch.save([x,y],'../data/x-files')
x2,y2=torch.load('../data/x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [8]:
mydict={'x':x,'y':y}
torch.save(mydict,'../data/mydict')
mydict2=torch.load('../data/mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [12]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net=MLP()
X=torch.randn(size=(2,20))
Y=net(X)

torch.save(net.state_dict(),'../data/mlp.params')

clone=MLP()
clone.load_state_dict(torch.load('../data/mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [13]:
Y_clone=clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])