In [2]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [4]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [5]:
inputs=pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [7]:
import torch
X=torch.tensor(inputs.to_numpy(dtype=float))
y=torch.tensor(outputs.to_numpy(dtype=float))
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [26]:
data_file=os.path.join('..','data','house_larger.csv')
with open(data_file,'w') as f:
    f.write('City,Location,Alley,NumRooms,Years,Price\n')
    f.write('Beijing,Downtown,Pave,4,20,3000000\n')
    f.write('Shanghai,NA,NA,3,NA,2700000\n')
    f.write('Beijing,Suburb,NA,NA,8,1000000\n')
    f.write('Shanghai,NA,Pave,NA,10,1500000\n')
    f.write('NA,Suburb,NA,2,5,2000000\n')
    f.write('Shanghai,NA,Pave,NA,NA,1600000\n')
    f.write('Beijing,Downtown,NA,1,NA,1500000\n')

data=pd.read_csv(data_file)
print(data)

       City  Location Alley  NumRooms  Years    Price
0   Beijing  Downtown  Pave       4.0   20.0  3000000
1  Shanghai       NaN   NaN       3.0    NaN  2700000
2   Beijing    Suburb   NaN       NaN    8.0  1000000
3  Shanghai       NaN  Pave       NaN   10.0  1500000
4       NaN    Suburb   NaN       2.0    5.0  2000000
5  Shanghai       NaN  Pave       NaN    NaN  1600000
6   Beijing  Downtown   NaN       1.0    NaN  1500000


In [27]:
inputs,outputs=data.iloc[:,0:5],data.iloc[:,5]
col=inputs.isna().sum().idxmax()    #缺失值最多的列(`Alley`)
del inputs[col]
inputs=inputs.fillna(inputs.mean())
print(inputs)

       City  Location  NumRooms  Years
0   Beijing  Downtown       4.0  20.00
1  Shanghai       NaN       3.0  10.75
2   Beijing    Suburb       2.5   8.00
3  Shanghai       NaN       2.5  10.00
4       NaN    Suburb       2.0   5.00
5  Shanghai       NaN       2.5  10.75
6   Beijing  Downtown       1.0  10.75


In [29]:
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Years  City_Beijing  City_Shanghai  City_nan  Location_Downtown  \
0       4.0  20.00             1              0         0                  1   
1       3.0  10.75             0              1         0                  0   
2       2.5   8.00             1              0         0                  0   
3       2.5  10.00             0              1         0                  0   
4       2.0   5.00             0              0         1                  0   
5       2.5  10.75             0              1         0                  0   
6       1.0  10.75             1              0         0                  1   

   Location_Suburb  Location_nan  
0                0             0  
1                0             1  
2                1             0  
3                0             1  
4                1             0  
5                0             1  
6                0             0  


In [30]:
X=torch.tensor(inputs.to_numpy(dtype=float))
y=torch.tensor(outputs.to_numpy(dtype=float))
X,y

(tensor([[ 4.0000, 20.0000,  1.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000],
         [ 3.0000, 10.7500,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,  1.0000],
         [ 2.5000,  8.0000,  1.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000],
         [ 2.5000, 10.0000,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,  1.0000],
         [ 2.0000,  5.0000,  0.0000,  0.0000,  1.0000,  0.0000,  1.0000,  0.0000],
         [ 2.5000, 10.7500,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,  1.0000],
         [ 1.0000, 10.7500,  1.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000]],
        dtype=torch.float64),
 tensor([3000000., 2700000., 1000000., 1500000., 2000000., 1600000., 1500000.],
        dtype=torch.float64))